const ACTIONS_TYPES = {
  //theme
  SET_THEME: "SET_THEME",
  //countries
  DATA_RESPONSE_SUCCESS: "DATA_RESPONSE_SUCCESS",
  DATA_RESPONSE_ERROR: "DATA_RESPONSE_ERROR",
  DATA_RESPONSE_IS_FETCHING_TRUE: "DATA_RESPONSE_IS_FETCHING_TRUE",
  DATA_RESPONSE_IS_FETCHING_FALSE: "DATA_RESPONSE_IS_FETCHING_FALSE",
  SET_INPUT_VALUE: "SET_INPUT_VALUE",
  SET_CHECKED_COUNTRY: "SET_CHECKED_COUNTRY",
  SET_REMOVED_COUNTRY: "SET_REMOVED_COUNTRY",
  //country
  DATA_INFO_RESPONSE_SUCCESS: "DATA_INFO_RESPONSE_SUCCESS",
  DATA_INFO_RESPONSE_ERROR: "DATA_INFO_RESPONSE_ERROR",
  DATA_INFO_RESPONSE_IS_FETCHING_TRUE: "DATA_INFO_RESPONSE_IS_FETCHING_TRUE",
  DATA_INFO_RESPONSE_IS_FETCHING_FALSE: "DATA_INFO_RESPONSE_IS_FETCHING_FALSE",
};

export default ACTIONS_TYPES;
